version: '3'
services:
  postgres-db:
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./src/launcher/db-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: default
      POSTGRES_PASSWORD: postgres

  axonserver:
    image: axoniq/axonserver:latest
    restart: unless-stopped
    ports:
     - "${AXON_SERVER_DASHBOARD_PORT}:8024"
     - "${AXON_SERVER_GRPC_PORT}:8124"
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx1g"

  keycloak:
    image: jboss/keycloak:latest
    restart: unless-stopped
    volumes:
      - ./keycloak/imports:/opt/jboss/keycloak/imports
      - ./keycloak/themes/custom:/opt/jboss/keycloak/themes/custom
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled
    ports:
      - "${KEYCLOAK_SERVER_PORT}:8080"
    depends_on:
      - postgres-db

