version: '3'
services:
  postgres-db:
    image: postgres:12-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./src/launcher/db-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: default
      POSTGRES_PASSWORD: postgres

  keycloak:
    image: jboss/keycloak
    command:
      -Djboss.http.port=${KEYCLOAK_SERVER_PORT}
    volumes:
      - ./keycloak/imports:/opt/jboss/keycloak/imports
      - ./keycloak/themes/custom:/opt/jboss/keycloak/themes/custom
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled
    ports:
      - "${KEYCLOAK_SERVER_PORT}:${KEYCLOAK_SERVER_PORT}"
    depends_on:
      - postgres-db

