version: '3'
services:
  postgres-db:
    image: postgres:12-alpine
    container_name: postgres-db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./src/launcher/db-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: default
      POSTGRES_PASSWORD: postgres

  mongo-db:
    image: mongo:4
    container_name: mongo-db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: test

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    links:
      - 'mongo-db:mongo'
    ports:
      - 8081:8081

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    command: 
      -Djboss.http.port=${KEYCLOAK_SERVER_PORT}
    volumes:
      - ./keycloak/imports:/opt/jboss/keycloak/imports
      - ./keycloak/themes/custom:/opt/jboss/keycloak/themes/custom
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled
    ports:
      - "${KEYCLOAK_SERVER_PORT}:${KEYCLOAK_SERVER_PORT}"
    depends_on:
      - postgres-db
