version: '3.7'
services:
  notebook:
    build:
      context: .
    container_name: jupyter-notebook
    volumes:
      - ./files:/home/jovyan/work
    network_mode: host
    environment:
      - JUPYTER_ENABLE_LAB=yes

